services:
  chat-svelte:
    container_name: ghcr.io/konixy/chat-svelte:latest
    image: chat-svelte:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    user: 'node'
    environment:
      - NODE_ENV=production
      - TZ=Europe/Paris
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 86:86
    extra_hosts:
      - 'mongoservice:172.17.0.1'
  chat-api-svelte:
    container_name: chat-api-svelte
    image: chat-api-svelte:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    user: 'node'
    environment:
      - NODE_ENV=production
      - TZ=Europe/Paris
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 87:87
    extra_hosts:
      - 'mongoservice:172.17.0.1'
